# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schemas/all_boolean.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19schemas/all_boolean.proto\"M\n\x05Proto\x12\x0c\n\x04opt1\x18\x01 \x01(\x08\x12\x0c\n\x04opt2\x18\x02 \x01(\x08\x12\x0c\n\x04opt3\x18\x03 \x01(\x08\x12\x0c\n\x04opt4\x18\x04 \x01(\x08\x12\x0c\n\x04opt5\x18\x05 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schemas.all_boolean_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTO._serialized_start=29
  _PROTO._serialized_end=106
# @@protoc_insertion_point(module_scope)
